-- begin SAD_ORDER
alter table SAD_ORDER add constraint FK_SAD_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references SAD_CUSTOMER(ID)^
create index IDX_SAD_ORDER_ON_CUSTOMER on SAD_ORDER (CUSTOMER_ID)^
-- end SAD_ORDER
-- begin SAD_ORDER_LINE
alter table SAD_ORDER_LINE add constraint FK_SAD_ORDER_LINE_ON_ORDER foreign key (ORDER_ID) references SAD_ORDER(ID)^
create index IDX_SAD_ORDER_LINE_ON_ORDER on SAD_ORDER_LINE (ORDER_ID)^
-- end SAD_ORDER_LINE
-- begin SAD_TERMINAL
alter table SAD_TERMINAL add constraint FK_SAD_TERMINAL_ON_AIRPORT foreign key (AIRPORT_ID) references SAD_AIRPORT(ID)^
create index IDX_SAD_TERMINAL_ON_AIRPORT on SAD_TERMINAL (AIRPORT_ID)^
-- end SAD_TERMINAL
-- begin SAD_MEETING_POINT
alter table SAD_MEETING_POINT add constraint FK_SAD_MEETING_POINT_ON_TERMINAL foreign key (TERMINAL_ID) references SAD_TERMINAL(ID)^
create index IDX_SAD_MEETING_POINT_ON_TERMINAL on SAD_MEETING_POINT (TERMINAL_ID)^
-- end SAD_MEETING_POINT
-- begin SAD_NOTE
alter table SAD_NOTE add constraint FK_SAD_NOTE_ON_MEETING_POINT foreign key (MEETING_POINT_ID) references SAD_MEETING_POINT(ID)^
create index IDX_SAD_NOTE_ON_MEETING_POINT on SAD_NOTE (MEETING_POINT_ID)^
-- end SAD_NOTE
