alter table SAD_MEETING_POINT add constraint FK_SAD_MEETING_POINT_ON_TERMINAL foreign key (TERMINAL_ID) references SAD_TERMINAL(ID);
create index IDX_SAD_MEETING_POINT_ON_TERMINAL on SAD_MEETING_POINT (TERMINAL_ID);
